In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr*20)
print(type(arr))

[ 20  40  60  80 100 120]
<class 'numpy.ndarray'>


In [4]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr.mean())
print(arr.sum())
print(arr.min())
print(arr.max())
print(arr.std())

3.5
21
1
6
1.707825127659933


In [6]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr[0])
print(arr[-1])
print(arr[1:3])


1
6
[2 3]


In [11]:
import numpy as np
matrix = np.array([[1,2,3], [7,8,9]])
print(matrix.shape)
print(matrix[0])
print(matrix[1, 2])


(2, 3)
[1 2 3]
9


In [14]:
import numpy as np
arr = np.arange(0, 22, 2)
print(arr)
print(arr[0: 3])



[ 0  2  4  6  8 10 12 14 16 18 20]
[0 2 4]


In [25]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr2 = np.ones(5)
print (arr1 + arr2)

[2. 3. 4. 5. 6.]
